### ISSUE TITLE
Item ID should be GUID instead of URL

### ISSUE THREAD

**Issue by alpipego** [manton/jsonfeed-wp#35]
Other WordPress feeds use the `guid` field as the feed id. If the URL changes, the ID of the element also changes if the plugin uses the URL.

**Comment by alpipego** [comment]
This can be achieved by replacing `get_permalink()` with `get_post_field('guid')` in 
https://github.com/manton/jsonfeed-wp/blob/68d8e8ccbd3f8fed31a5eb954924031077cceec6/feed-json-functions.php#L113

**Comment by dshanske** [comment]
https://jsonfeed.org/version/1 The spec recommends it be the id

**Comment by dshanske** [comment]
@manton Do you have a thought here?

**Comment by alpipego** [comment]
The `guid` is the "Global Unique Identifier" so it kinda is the ID. Other feeds use it, that's why I suggested it.

**Comment by dshanske** [comment]
At this time, while I understand the point, going with the guidance of the specification

**Comment by alpipego** [comment]
This part of the specification?

> id (required, string) is unique for that item for that feed over time. If an item is ever updated, the id should be unchanged. New items should never use a previously-used id. If an id is presented as a number or other type, a JSON Feed reader must coerce it to a string. Ideally, the id is the full URL of the resource described by the item, since URLs make great unique identifiers.

That's why I proposed the change. The GUID is exactly there for this reason and immutable. The permalink is not, however.

**Comment by dshanske** [comment]
In the absence of any comment from the spec co-developer on the matter, will go with the guid. Especially considering that @manton's micro.blog uses an ID number, not a permalink.

**Comment by manton** [comment]
Whoops, sorry I missed this discussion. I think either approach can work depending on the context. Actually in Micro.blog, I use a number for `id` sometimes and a URL other times.

The downside to switching this is that most feed readers will think your existing blog posts are new again. But it's a one-time cost, and since this has shipped in the latest version of the plugin, I only mention it because we probably should stick with GUIDs from now on.
